### ISSUE TITLE
MSBuild Integration

### ISSUE THREAD

**Issue by KubaO** [c80k/capnproto-dotnetcore#12]
Using capnpc-csharp without build integration is painful. Let's add MSBuild integration.

I currently have a less fleshed-out solution to this (it also integrates the capnproto c++ project within the solution), but SpecFlow's example is more comprehensive. Thus, the custom code generator task and other miscellanea can be modeled on:

- [SpecFlow.Tools.MsBuild.Generation][1].
- https://hmemcpy.com/2015/03/adding-a-custom-property-page-to-existing-project-types-in-visual-studio/
- https://github.com/ic3y808/SLTools

[1]: https://github.com/techtalk/SpecFlow/tree/master/SpecFlow.Tools.MsBuild.Generation

**Comment by c80k** [comment]
If I got that right, you're seeking for a convient&integrated way for C# generation from .capnp during design-time (much like SpecFlow)? I agree that this would be a neat feature.

I already experimented with such and related ideas, but I have little to no experience with the required technologies. The big picture:
- Syntax highlighting for .capnp files. Could be done with a VSIX plugin. A [Cap'n Proto Textmate grammar](https://github.com/textmate/capnproto.tmbundle) already exists.
- Nice-to-have: .capnp syntax completion. Would clearly require much more effort and could be postponed.
- Most important: Code generation from .capnp: I had some success with altering the [SingleFileGeneratorSample](https://github.com/madskristensen/SingleFileGeneratorSample), but I didn't get this to work reliably, and it is different from MSBuild integration(?). This approach is limited to one generated file per schema. Unsure whether this is acceptable in the presence of imports.
- Generally, a good MSBuild integration would let the user decide which language to generate for. Maybe, I need to configure additional command-line arguments (-I) or a particular working directory. How do I specify that from inside the IDE?

Do you have some experience with that? Any suggestions?

BTW: A very basic solution is to configure a VS external tool.
Command line: ...\capnp.exe
Arguments: compile -ocsharp $(ItemPath)

Of course, this needs to be done individually, and it does not allow for variable additional options.

**Comment by KubaO** [comment]
I have experience in the sense that I got it working once (on a solution that includes both csharp and c++ capnproto), and that I think I understand how the MsBuild.Generation flow works.

MSBuild's integration with C++ and C# build flows is poorly documented, so the best bet is to start with something that works and is maintained by at least some MSFT people. SpecFlow is just such a project.

There will be a project property where you can choose `capnp.exe` to use. It can also be a project within the solution itself that builds it - for full from-scratch builds. Includes etc. can also be added to the project property page.

Everything else will be basically copypasta from SpecFlow, removal of SpecFlow-specific code (mostly confined to separate files), and modifications specific to capnproto and capnpc-csharp.

My goal is for it to be completely seamless, i.e. just put some `.capnp` files in the solution, and they get processed (with option to move them to `None` item group to exclude from generation). This must work both for stand-alone MSBuild builds (from command line), from user-triggered builds in Visual Studio (e.g. via F7), and from IntelliSense builds that are executed internally by Visual Studio.

This issue is for MSBuild integration only. Syntax highlighting, completion (i.e. code analysis for .capnp) etc. belong in their own issues :)

Since this project is C#-specific, generation of C++ files is outside of scope I believe, and there is always only one `.cs` file generated per schema, although that's not an inherent limitation, just a fact based on what `capnpc-csharp` does.

**Comment by c80k** [comment]
Sounds good. I digged a bit into the SpecFlow build integration code, and it seems viable. Some questions:

- Assuming that this MSBuild integration is for C# only: Maybe one day, someone else will provide another MSBuild integration for C++. So we'd have two (or more) integrations for the same input file extension (.capnp). Do you think they would interfere, introducing problems inside mixed C# / C++ solutions?
- Besides the build-triggers you mentioned, I'd like to support ad-hoc code generation (or is that what you mean by IntelliSense build?). The generation shall either be triggerable by context menu command (like SpecFlow does it) or by saving the schema file (like T4 text templates do it). I think this is important for interactive development workflows. Is that possible with MSBuild integration, or would that require a VSIX?
- Could you elaborate more on adding capnp import directories (and other options) to the project property page? How would this look like?

**Comment by KubaO** [comment]
There will be no interference I don't think, because the assignment is between the `.capnp` extension and `CapnpSchema` items only provides the information that "these are the schemas" we care about. Within any particular project, those schemas will be processed only by the targets associated with a particular project type, i.e. `csproj` vs `vcxproj`.

The code generation will happen during build time, so if you don't exclude the schema file, then it will be automatically generated every time it's changed, during "design" time (i.e. when you edit the code). The context menu can be provided when the former somehow wouldn't work. This is all handled via msbuild project files, since they are processed by the IDE as well. If there's a need to add a VSIX then I don't see this as a problem, since an extension is needed for property pages anyway.

The project property page would literally be an additional page that you see in project properties, titled "Capnproto Schemas", where you can specify e.g. the input path, the location of `capnp.exe` or the name of the project generating it, the optional output (e.g. a binary with evaluated constants), and so on. This would be just a nice UI for properties set in the `.csproj` / `.vcxproj`.

**Comment by c80k** [comment]
Here is some work in progress:
https://github.com/c80k/capnproto-dotnetcore/tree/msbuild-integration
Currently, this is not yet integrated with capnpc-csharp. It just recognized .capnp files and generates a .capnp.cs with dummy comment inside. But those missing pieces will be quire straightforward.

**Comment by c80k** [comment]
Now available on master. Any feedback is appreciated. If there are no major issues I will trigger a new release next week.

**Comment by KubaO** [comment]
Thank you so much for working on this!
