### ISSUE TITLE
Issue with serializing generic types

### ISSUE THREAD

**Issue by BuBuMan** [c80k/capnproto-dotnetcore#20]
Hey, 

I have a couple of questions with the C# implementation of Cap'n Proto.

1) Is there an easy way to convert a WireFrame to a byte array? I would like to use a custom transport layer to write to a stream and not use the FramePump.

2) I have been playing around with the serialization and ran into a serialization issue when dealing with Generics. Below is a snippet of my code. I was trying to achieve something similar shown in the wiki https://github.com/c80k/capnproto-dotnetcore/wiki/Example-application-(non-RPC)

However I get an invalid cast exception when rpcRequest.serialize(root) is executed. Any Idea why this is happening?

```

static void Main(string[] args)
{
    RpcRequest<ArithmeticOperationRequest> rpcRequest = new RpcRequest<ArithmeticOperationRequest>();
    rpcRequest.Method = "AddTwoNumbers";

    ArithmeticOperationRequest request = new ArithmeticOperationRequest();

    request.NumA = 5;
    request.NumB = 8;

    rpcRequest.Request = request;

    var msg = MessageBuilder.Create();
    var root = msg.BuildRoot<RpcRequest<ArithmeticOperationRequest>.WRITER>();
    rpcRequest.serialize(root);

    var mems = new MemoryStream();
    var pump = new FramePump(mems);
    pump.Send(msg.Frame);
    mems.Seek(0, SeekOrigin.Begin);

    var frame = Framing.ReadSegments(mems);
    var deserializer = DeserializerState.CreateRoot(frame);
    var mainRequest = new RpcRequest<ArithmeticOperationRequest>.READER(deserializer);
    var innerRequest = new ArithmeticOperationRequest.READER(mainRequest.Request);

    Console.WriteLine("Method Name: " + mainRequest.Method);
    Console.WriteLine("NumA: " + innerRequest.NumA.ToString());
    Console.WriteLine("NumB: " + innerRequest.NumB.ToString());
}

```

Here is how my capnp file look like for reference. 

```

struct RpcRequest(Request) 
{
	method @0 :Text;
	request @1 :Request;
}

struct ArithmeticOperationRequest
{
	numA @0 :Int32;
	numB @1 :Int32;
}

struct ArithmeticOperationReply
{
	result @0 :Int32;
}

```

**Comment by c80k** [comment]
Hi,

1. `WireFrame.Segments` contains the message raw data. Each segment essentially is a byte array, except that it is stored as an array of 64-bit words. To re-align it as byte array, you may do it like `FramePump` does internally: 

```csharp
WireFrame myFrame = ...;
for (int i = 0; i < myFrame.Segments.Count)
{
  var bytes = MemoryMarshal.Cast<ulong, byte>(myFrame.Segments[i].Span).ToArray();
  // do something with the bytes
}
```

2. I consider this a bug in the domain class API. You may work around it by using the "classic" writers:

```csharp
   var msg = MessageBuilder.Create();
   var root = msg.BuildRoot<RpcRequest<ArithmeticOperationRequest>.WRITER>();
   var request = msg.CreateObject<ArithmeticOperationRequest.WRITER>();
   request.NumA = 5;
   request.NumB = 8;
   root.Method = "AddTwoNumbers";
   root.Request = request.Rewrap<DynamicSerializerState>();
 
   var mems = new MemoryStream();
   var pump = new FramePump(mems);
   pump.Send(msg.Frame);
   mems.Seek(0, SeekOrigin.Begin);

   var frame = Framing.ReadSegments(mems);
   var deserializer = DeserializerState.CreateRoot(frame);
   var mainRequest = new RpcRequest<ArithmeticOperationRequest>.READER(deserializer);
   var innerRequest = new ArithmeticOperationRequest.READER(mainRequest.Request);

   Console.WriteLine("Method Name: " + mainRequest.Method);
   Console.WriteLine("NumA: " + innerRequest.NumA.ToString());
   Console.WriteLine("NumB: " + innerRequest.NumB.ToString());

```

**Comment by BuBuMan** [comment]
Hey,

Thanks for your reply! :) Just a follow up question on the WireFrame. Converting from WireFrame to a byte array is pretty straight forward but converting the other way round seems a bit more complicated. I noticed that the FramePump writes how many segments and how big each segment is in the beginning so that when it reads it later it knows how to convert it back. 

My use case is that I will be sending a byte array back and forth from a C# application to a C++ application. Below is how I am converting words to a byte array and vice versa (char*) in C++

```

// Convert Message to a byte array
kj::Array<capnp::word> words = capnp::messageToFlatArray(message);	

char* buffer = new char[words.asChars().size()];
memcpy(buffer, words.asChars().begin(), words.asChars().size());

// Send response to C# application...

```

```

// Convert byte array to a message
kj::Array<capnp::word> words= kj::heapArray<capnp::word>(byteArraySize);
memcpy(words.asChars().begin(), buffer, words.asChars().size());
capnp::FlatArrayMessageReader reader(words);

```

Does the above messageToFlatArray method include number of segments and size of segments in the beginning? Also does the FlatArrayMessageReader expect those values to be there? If yes, then I guess I can do exactly what the framePump is doing. Otherwise I need to figure out how to convert the byte array to a WireFrame so I can serialize the message on the C# side.

I will be testing the above later today when I get time. 

Thanks again for your help!

**Comment by c80k** [comment]
The `FramePump` serialization behaves as specified here: https://capnproto.org/encoding.html#serialization-over-a-stream

I never used `capnp::messageToFlatArray` so far, so sorry, I cannot tell what it does exactly. However, I would expect it to implement the framing (especially because there is an overload which accepts an array of segments, which is technically the C++ counterpart of `WireFrame`).

**Comment by BuBuMan** [comment]
Thanks for your reply. I was able to test and indeed messageToFlatArray implements the framing. 

I ran into another issue today. I was able to send some messages back and forth between C++ and C# application. However some messages failed to serialize on the C++ side using the capnp::FlatArrayMessageReader.

Debugging the issue further it seems like the WireFrame in C# does not match the C++ implementation in some cases. I have written simple code in C++ and C# to demonstrate the issue.

C++

```

int main()
{
	capnp::MallocMessageBuilder message;

	RpcRequest<PrintPlayerDataRequest>::Builder rpcRequest = message.initRoot<RpcRequest<PrintPlayerDataRequest>>();
	rpcRequest.setMethod("PrintHookParameters");

	capnp::MallocMessageBuilder innerMessage;
	PrintPlayerDataRequest::Builder printPlayerDataRequest = innerMessage.initRoot<PrintPlayerDataRequest>();
	printPlayerDataRequest.setPlayerName("Bob");
	printPlayerDataRequest.setHealth(100);
	printPlayerDataRequest.setIsInvincible(true);
	printPlayerDataRequest.setGravity(9.8f);

	rpcRequest.setRequest(printPlayerDataRequest);

	kj::Array<capnp::word> words = capnp::messageToFlatArray(message);

	return 0;
}

```

C#

```

static void Main(string[] args)
{
    var msg = MessageBuilder.Create();
    var root = msg.BuildRoot<RpcRequest<PrintPlayerDataRequest>.WRITER>();            
    root.Method = "PrintHookParameters";

    var request = msg.CreateObject<PrintPlayerDataRequest.WRITER>();            
    request.PlayerName = "Bob";
    request.Health = 100;
    request.IsInvincible = true;
    request.Gravity = 9.8f;
    root.Request = request.Rewrap<DynamicSerializerState>();

    var frame = msg.Frame;
}

```

Since the Frame has only 1 segment in this case we can directly compare how the memory layout looks like between the segment in the frame and the words in C++. The first word in C++ is Ignored since it describes the framing.

Upon examination the memory in C# looks like this:

00 00 00 00 00 00 02 00 05 00 00 00 a2 00 00 00 00 00 00 00 00 00 00 00 50 72 69 6e 74 48 6f 6f 6b 50 61 72 61 6d 65 74 65 72 73 00 00 00 00 00 42 6f 62 00 00 00 00 00 64 00 00 00 01 00 00 00 cd cc 1c 41 00 00 00 00 f1 ff ff ff 22 00 00 00

The memory in C++ looks like this:

00 00 00 00 00 00 02 00 05 00 00 00 a2 00 00 00 0c 00 00 00 02 00 01 00 50 72 69 6e 74 48 6f 6f 6b 50 61 72 61 6d 65 74 65 72 73 00 00 00 00 00 64 00 00 00 01 00 00 00 cd cc 1c 41 00 00 00 00 01 00 00 00 22 00 00 00 42 6f 62 00 00 00 00 00

Copying the above in a text editor, you can directly see some discrepancies between the two.

Doing the test with the ArithmeticOperationRequest in the previous comment, you would get the exact memory layout in both C++ and C#. 

Am I missing something here? 

Here is the Capnp definition for reference

```
struct RpcRequest(Request) 
{
	method @0 :Text;
	request @1 :Request;
}

struct PrintPlayerDataRequest 
{
	playerName @0 :Text;
	health @1 :Int32;
	isInvincible @2 :Bool;
	gravity @3 :Float32;
}

```

Thanks a lot for your time.

**Comment by c80k** [comment]
As long as you don't see any incorrect field values, this is fine. It is up to the implementation where to allocate storage for data. Taking your example, the implementation may decide where to put the RpcRequest.method string, the RpcRequest.request struct, and the PrintPlayerDataRequest.playerName string. It seems that the C++ / C# side just serialize them in a slightly different order.

**Comment by BuBuMan** [comment]
The issue is that C++ FlatArrayReader does not serialize the data correctly. 

I get the method name in RpcRequest, but then PrintPlayerDataRequest has all values uninitialized =/

**Comment by BuBuMan** [comment]
I wrote code that reproduces the exact issue. I hardcoded the flat array buffer I get from C# and C++ and try to serialize my messages. 

```

#include "HookMessages.capnp.h"
#include <capnp/message.h>
#include <capnp/serialize-packed.h>
#include <iostream>

void Serialize(char* data, int size);

int main()
{
	const int size = 88;
	char cpp_data[size] =		{ 0x00, 0x00, 0x00, 0x00, 0x0a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x05, 0x00, 0x00, 0x00, 0xa2, 0x00, 0x00, 0x00, 0x0c, 0x00, 0x00, 0x00, 0x02, 0x00, 0x01, 0x00, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x48, 0x6f, 0x6f, 0x6b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x00, 0x00, 0x00, 0x00, 0x00, 0x64, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0xcd, 0xcc, 0x1c, 0x41, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x22, 0x00, 0x00, 0x00, 0x42, 0x6f, 0x62, 0x00, 0x00, 0x00, 0x00, 0x00 };
	char csharp_data[size] =	{ 0x00, 0x00, 0x00, 0x00, 0x0a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x05, 0x00, 0x00, 0x00, 0xa2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x48, 0x6f, 0x6f, 0x6b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x00, 0x00, 0x00, 0x00, 0x00, 0x42, 0x6f, 0x62, 0x00, 0x00, 0x00, 0x00, 0x00, 0x64, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0xcd, 0xcc, 0x1c, 0x41, 0x00, 0x00, 0x00, 0x00, 0xf1, 0xff, 0xff, 0xff, 0x22, 0x00, 0x00, 0x00 };

	std::cout << "C++ Serialization: " << std::endl;
	Serialize(cpp_data, size);

	std::cout << std::endl << "C# Serialization: " << std::endl;
	Serialize(csharp_data, size);

	return 0;
}

void Serialize(char* data, int size)
{
	kj::Array<capnp::word> words = kj::heapArray<capnp::word>(size);
	memcpy(words.asChars().begin(), data, size);

	capnp::FlatArrayMessageReader reader(words);

	auto rpcRequest = reader.getRoot<RpcRequest<PrintPlayerDataRequest>>();
	std::cout << "MethodName " << rpcRequest.getMethod().cStr() << std::endl;
	std::cout << "PlayerName: " << rpcRequest.getRequest().getPlayerName().cStr() <<std::endl;
	std::cout << "Health: " << rpcRequest.getRequest().getHealth() << std::endl;
	std::cout << "Gravity: " << rpcRequest.getRequest().getGravity() << std::endl;
	std::cout << "IsInvincible: " << rpcRequest.getRequest().getIsInvincible() << std::endl;
}

```

**Comment by c80k** [comment]
Never mind. Commit https://github.com/c80k/capnproto-dotnetcore/commit/9a121245744390dce565adda3f8c9b594e3c13c1 should fix the invalid cast exception.

**Comment by BuBuMan** [comment]
Thanks a lot for the fix! This will make it much cleaner to use :)
