### ISSUE TITLE
Problem when using a generic method

### ISSUE THREAD

**Issue by bergm** [c80k/capnproto-dotnetcore#25]
Hello,

I've got the problem that in my schemas I have an interface CapHolder which is supposed to hold simply all kinds of capabilites. Additionally a CapHolder has a method to free this capability on the server side when the clients wants to and also a method to return a restoreToken to restore the capability later. For that reason the CapHolder has a generic type parameter. (I left out all unnecessary stuff)

```capnp
interface A {
  methodA @0 () -> (result :Int64);
}

interface CapHolder(CapType) {
  cap @0 () -> (cap :CapType);
}

interface CapHolderA {
  cap @0 () -> (cap :A);
}

interface B {
  getAinCapHolderAnyPointer @0 () -> (aInCapHolder :CapHolder);
  getAinCapHolderGenericA @1 () -> (aInCapHolder :CapHolder(A));
  getAinCapHolderNonGenericA @2 () -> (aInCapHolder :CapHolderA);
}
```

In my minimal example I want to get a bootstrap capability to an object B and from there get a capability to a CapHolder which holds an capability to an object A. B has three methods, the non generic one works, but the others don't. 
I tested it with a minimal PyCapnp server implementation and PyCapnp might have bug or problem with the generic :CapHolder(A). At least the error message of the C# version is different and points to dynamic.c++ in the underlying library. But getAinCapHolderAnyPointer at least should work. But there I get an exception when the C# impl tries to deserialize the returned AnyPointer generic result struct from getAinCapHolderAnyPointer in line 3 capholderAPT.Wait().

```csharp
var b = client.GetMain<CapnpGen.IB>();
var capholderAPT = b.GetAinCapHolderAnyPointer();
capholderAPT.Wait();
var capholderAP = capholderAPT.Result;
var capAPT = capholderAP.Cap();
capAPT.Wait();
```

I get this error message.

System.AggregateException: 'One or more errors occurred. (Cannot create an instance of Capnp.Rpc.CapabilityReflection+ProxyFactory`1[CapnpGen.CapHolder_Proxy`1[CapnpGen.CapHolder_Proxy`1[TCapType]]] because Type.ContainsGenericParameters is true.)'

Even though I tried to debug into it, I don't understand right now what's the problem. Help's highly appreciated.

???

Cheers, Michael

[problem-generic-method.zip](https://github.com/c80k/capnproto-dotnetcore/files/3772660/problem-generic-method.zip)

**Comment by c80k** [comment]
D'oh!

```csharp
proxyClass = proxyClass.MakeGenericType(proxyClass);
```

...should be:

```csharp
proxyClass = proxyClass.MakeGenericType(genericArguments);
```

That's pretty much the essence of the bug. But some more changes are required. The generated domain classes should not map a capnp "AnyPointer" to the C# library type "Capnp.AnyPointer" (despite it feels tempting). "object" should be the better choice.

**Comment by c80k** [comment]
See latest commit, test case "Issue25"

**Comment by bergm** [comment]
Thank you. 👍
