### ISSUE TITLE
How to add namespaces?

### ISSUE THREAD

**Issue by BuBuMan** [c80k/capnproto-dotnetcore#27]
Hey,

Is it possible to add namespaces to the generated files? The c++ version requires an import of a capnp file. For example:

```
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("foo::bar::baz");
```

I am having a hard time to find something similar in the C# repository. 

Thanks

**Comment by c80k** [comment]
Hi,
yes, this is possible. The code generator understands the `Cxx.namespace` attribute and converts the desired namespace to C# syntax convention. `foo::bar::baz` would become `Foo.Bar.Baz`.

Cheers!

**Comment by c80k** [comment]
Feel free to file a new issue if the given approach doesn't solve your request.

**Comment by BuBuMan** [comment]
Forgot to reply after the suggestion. Works fine! Thanks :)
