### ISSUE TITLE
Does the project target .NET standard 2.0 or 2.1?

### ISSUE THREAD

**Issue by alexcamposruiz** [c80k/capnproto-dotnetcore#28]
I noticed that the implementation uses [System.Span](https://docs.microsoft.com/en-us/dotnet/api/system.span-1) or [MemoryMarshal](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.memorymarshal?view=netcore-3.0), which are only available since .NET Standard 2.1

**Comment by c80k** [comment]
The VS solution targets .NET Standard 2.0 and .NET Core 2.1. The .NET Standard 2.0 variant works around the missing APIs using conditional compilation. The workarounds are certainly not very efficient, so the price is performance.

**Comment by alexcamposruiz** [comment]
Thanks for the explanation
