### ISSUE TITLE
Not sure how to proceed on MacOS

### ISSUE THREAD

**Issue by l1x** [c80k/capnproto-dotnetcore#30]
Hi,

I have followed your documentation up to the point when I have compiled capnproto-dotnetcore/capnpc-csharp successfully on my laptop.

If I understand correctly the next step is to invoke the code generation like this:

`capnp compile -o"...capnproto-dotnetcore/capnpc-csharp/bin/release/netcoreapp2.1/" avsc.capnp`

Unfortunately, it results in the following:

```
*** Uncaught exception ***
capnp/compiler/capnp.c++:600: failed: exec(): Permission denied
stack: 10435978b 10441a188 104419fd2
/Users/l1x/code/lambda/capnproto-dotnetcore/capnpc-csharp/bin/release/netcoreapp2.1/: plugin failed: exit code 1

```
Is there anything I could do about this?

**Comment by c80k** [comment]
Hi,

I'd like to let the go ahead to anybody with Mac OS experience.

The path to the generator plugin must point to an executable. Your path seems like a folder to me. It should actually look similar to this:

```
capnp compile -o"...capnproto-dotnetcore/capnpc-csharp/bin/release/netcoreapp2.1/osx.10.11-x64/capnpc-csharp" avsc.capnp
```

**Comment by l1x** [comment]
Thanks!
