### ISSUE TITLE
Performance comparison with GRPC

### ISSUE THREAD

**Issue by bombompb** [c80k/capnproto-dotnetcore#40]
As CapnProto advertises to be: 

> an insanely fast data interchange format and capability-based RPC system

I did a Benchmark between GRPC and CapnProto (v1.2.138) by sending an object of 2 [MB] from a client to an echo server (which deserializes the received object and then serializes it again) and echos it back to the sender/client. On the client side it is also serialized before sending and deserialized on receiving it back from the echo server. The time is measured on the client side between the start of serializing the object (just before sending) and after having deserialized it back (after receiving it back).

The CapnProto is really slow compared to GRPC (See graph below)
![Performance](https://user-images.githubusercontent.com/23037604/73725799-7417b580-472e-11ea-9ae0-7b3cd9e4548a.PNG)

When running CapnProto benchmark from within a .NET core assembly the performance improves with a factor 2. However this is still not the performance I would expect from CapnProto.

Please investigate what is causing this.

**Comment by c80k** [comment]
Hi,
would you please share more details on your benchmark? RPC schema, ideally the whole benchmarking code? Your data suggests that a single roundtrip requires more than 3s, which seems implausibly high.
Generally, the .NET Core variant will always be faster than .NET Framework because it benefits from `Span<T>` (less memory allocations+copying). Your measurement seems to confirm that. However, this .NET-based implementation will probably never be as fast as the [original native implementation](https://capnproto.org/)
To enable a fair comparison (especially for discussing whether it's the protocol or its implementation), the following points would be of interest:

- Measure performance with the [original implementation](https://capnproto.org/) an provide it for reference.
- For the GRPC case: Which target language did you use inside your benchmarking code? C++? C#?

**Comment by c80k** [comment]
I recently [added some benchmarks](https://github.com/c80k/capnproto-dotnetcore/tree/master/Benchmarking) on my own.

It is basically a comparison of the gRPC .NET implementation (more precisely: Grpc.AspNetCore at server side; Google.Protobuf, Grpc.Net.Client, Grpc.Tools at client side) with this Cap'n Proto implementation. GRPC server, Cap'n Proto server, and both clients (which do the profiling) are all implemented in C# and are running in a .NET Core 3.1 environment.

The profiled RPC is an "Echo", as initially described.

Cap'n Proto schema:
```capnp
interface Echoer {
  echo @0 (input : Data) -> (output : Data);
}
```

Protobuf schema:
```protobuf
syntax = "proto3";

service Echoer {
  rpc Echo (EchoRequest) returns (EchoReply);
}

message EchoRequest {
  bytes payload = 1;
}

message EchoReply {
  bytes payload = 1;
}
```

The performance measurements are done with the help of [BenchmarkDotNet](https://benchmarkdotnet.org/). The payload size varies from 20 bytes to 2 MB. Here is what I got:

**capnproto-dotnetcore**
``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18362
Intel Core i7-9700K CPU 3.60GHz (Coffee Lake), 1 CPU, 8 logical and 8 physical cores
.NET Core SDK=3.1.101
  [Host]     : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT  [AttachedDebugger]
  DefaultJob : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT


```
| Method | PayloadBytes |         Mean |     Error |    StdDev |
|------- |------------- |-------------:|----------:|----------:|
|   **Echo** |           **20** |     **104.4 us** |   **1.96 us** |   **1.93 us** |
|   **Echo** |          **200** |     **113.2 us** |   **1.46 us** |   **1.37 us** |
|   **Echo** |         **2000** |     **298.4 us** |   **5.76 us** |   **7.49 us** |
|   **Echo** |        **20000** |   **1,587.5 us** |   **9.83 us** |   **8.71 us** |
|   **Echo** |       **200000** |  **14,408.5 us** |  **83.98 us** |  **74.45 us** |
|   **Echo** |      **2000000** | **140,330.3 us** | **874.98 us** | **818.45 us** |

**gRPC for .NET**

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18362
Intel Core i7-9700K CPU 3.60GHz (Coffee Lake), 1 CPU, 8 logical and 8 physical cores
.NET Core SDK=3.1.101
  [Host]     : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT  [AttachedDebugger]
  DefaultJob : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT


```
| Method | PayloadBytes |        Mean |     Error |    StdDev |
|------- |------------- |------------:|----------:|----------:|
|   **Echo** |           **20** |    **119.6 us** |   **0.99 us** |   **0.88 us** |
|   **Echo** |          **200** |    **119.2 us** |   **0.70 us** |   **0.65 us** |
|   **Echo** |         **2000** |    **130.3 us** |   **1.52 us** |   **1.42 us** |
|   **Echo** |        **20000** |    **183.4 us** |   **1.15 us** |   **1.07 us** |
|   **Echo** |       **200000** |  **1,269.6 us** |  **25.37 us** |  **56.73 us** |
|   **Echo** |      **2000000** | **12,146.5 us** | **204.63 us** | **181.40 us** |

For payloads up to 200 bytes, capnproto-dotnetcore performs slightly better than gRPC. But obviously, it does not scale well with payload size. I don't see any fundamental reason why this should be the case. From an implementation point of view, the serializer classes show some potential for micro optimizations. Chances are good for getting that thing faster.

Cheers!

**Comment by bombompb** [comment]
Great you could reproduce it the same way I did. Indeed for smaller payloads it is performing ok, but once you start sending bigger blobs (like images), it does not perform any more. Thanks for looking into it.

**Comment by c80k** [comment]
I've created a [branch for performance tuning](https://github.com/c80k/capnproto-dotnetcore/tree/performance). Results look quite promising. Tweaks in the serializer/deserializer classes for primitive elements lead to a drastical improvements for large payloads. Intermediate buffering (BufferedStream) improved the performance also for small payloads.

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18362
Intel Core i7-9700K CPU 3.60GHz (Coffee Lake), 1 CPU, 8 logical and 8 physical cores
.NET Core SDK=3.1.101
  [Host]     : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT
  DefaultJob : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT


```
| Method | PayloadBytes | BufferSize |        Mean |     Error |     StdDev |      Median |
|------- |------------- |----------- |------------:|----------:|-----------:|------------:|
|   **Echo** |           **20** |       **1024** |    **61.59 us** |  **0.768 us** |   **0.718 us** |    **61.29 us** |
|   **Echo** |          **200** |       **1024** |    **60.04 us** |  **0.144 us** |   **0.135 us** |    **60.02 us** |
|   **Echo** |         **2000** |       **1024** |    **74.64 us** |  **0.217 us** |   **0.192 us** |    **74.65 us** |
|   **Echo** |        **20000** |       **1024** |    **98.83 us** |  **0.918 us** |   **0.858 us** |    **98.69 us** |
|   **Echo** |       **200000** |       **1024** |   **247.98 us** |  **3.395 us** |   **3.009 us** |   **247.85 us** |
|   **Echo** |      **2000000** |          **0** | **2,264.42 us** | **44.475 us** |  **71.820 us** | **2,290.64 us** |
|   **Echo** |      **2000000** |       **1024** | **3,099.38 us** | **61.726 us** | **143.060 us** | **3,154.17 us** |
|   **Echo** |      **2000000** |       **4096** | **3,093.28 us** | **61.388 us** | **115.301 us** | **3,108.63 us** |

**Comment by bombompb** [comment]
Great work, now it is also beating GRPC. Thanks.

**Comment by MoodieG** [comment]
Do you plan on pushing this to Master soon? The performance improvements are pretty drastic.

**Comment by c80k** [comment]
I pushed it yesterday, enjoy! :-)
The next release, however, will still need some time. I'm in the middle of improving code coverage, analyzing and fixing the unveiled issues...

**Comment by c80k** [comment]
Took quite long, version 1.3.118 now officially integrates the said improvements. I recommend using the released version, since it also contains several concurreny bug fixes. I'll close this issue now.
