### ISSUE TITLE
CS 2046 on basic project setup

### ISSUE THREAD

**Issue by ekirchdev** [c80k/capnproto-dotnetcore#43]
I have the following setup
- Visual Studio 2019
- .NET Core 2.1 project
- added CapnpC.CSharp.MsBuild.Generation v1.2.138 via NuGet

I want to generate code during build by using the very simple schema from here: https://capnproto.org/language.html

The compiler throws several CS 2046 errors. It says it could not recognize the generated annotations "TypeId" and "TypeIdAttribute":

```
namespace CapnpGen
{
    [TypeId(0xed5bcc458b243f52UL)]
    public class Person : ICapnpSerializable
    {
        public const UInt64 typeId = 0xed5bcc458b243f52UL;
        void ICapnpSerializable.Deserialize(DeserializerState arg_)
        {
```

Am I missing something?

**Comment by c80k** [comment]
This is defined in `Capnp.Net.Runtime`. Did you install it?

**Comment by ekirchdev** [comment]
Yes, I did!
![image](https://user-images.githubusercontent.com/47575839/74652840-37fd3f80-5187-11ea-84c2-c9bce534de40.png)

**Comment by c80k** [comment]
From where did you install that assembly? Version 1.0.0 seems seriously outdated and was never published.

`Install-Package Capnp.Net.Runtime -Version 1.2.189`

**Comment by ekirchdev** [comment]
Now it seems to work! Thanks.

The problem occurred, because I installed `CapnpC.CSharp.MsBuild.Generation` first. NuGet says, it requires `Capnp.Net.Runtime (>= 1.0.0)` --> so it installed `Capnp.Net.Runtime` in version `1.0.0`.
