### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by ChangeCraft** [c80k/capnproto-dotnetcore#47]
There is a huge lack of documentation. As a newbie in this area it's nearly impossible for me to use the C# implementation of the Capnproto API apart from the most basic stuff that can be derived from the example in the wiki. Can we please get at least some documentation on the advanced stuff like the server calling functions on the server etc...
If I am missing any source of information where I can read up on said stuff please correct me.

**Comment by c80k** [comment]
While [Example application (RPC)
](https://github.com/c80k/capnproto-dotnetcore/wiki/Example-application-(RPC)) gives an entry point, every public class, interface, method etc. is decorated with a documentation comment. When using VS as IDE, these comments should pop up automatically.
 
If you'd like to dive deeper, you may have a look at the test cases inside Capnp.Net.Runtime.Tests.*. They contain lots of client/server implementations, including capability-passing across calls. Some test suites are an idiomatic port of their [C++ reference implementation](https://github.com/capnproto/capnproto) equivalents.

For now, I don't have resources for extending the documentation wiki. Current focus is on quality: stability, correctness, test coverage etc. If you have a particular question, I will try to help you out.

**Comment by ChangeCraft** [comment]
Ahh well I missed those.
The thing I couldn't figure out is how to implement an interface that is called from the server on the client side.

**Comment by c80k** [comment]
During the last weeks a heavily invested in writing Wiki pages. I hope that all relevant aspects are covered now in both code documentation and editorial content. So I'll close this issue now.
