### ISSUE TITLE
Generate structs instead of classes?

### ISSUE THREAD

**Issue by kwinz** [c80k/capnproto-dotnetcore#48]
I usually make C# arrays of structs to have control over the memory layout.
Is there a reason why the CapnpGen objects are designed to be generated classes instead of structs?
Struct could still inherit from ICapnpSerializable or you could pass the struct (or a `ref` to the struct) to another class that does the serialization.
I am new to capnproto so excuse me if this a naive question. Thanks for the advice!

[1] https://stackoverflow.com/a/171090/643011

**Comment by c80k** [comment]
First, it is hard (if not impossible) to map capnp raw struct data directly to a C# struct. Main obstables:
- the [pointer section](https://capnproto.org/encoding.html#structs), which refers to other locations inside its segment or foreign segments
- compatibility rules, which allow a struct to be extended later on. 

Second, the performance benefit would be questionable. While a struct would save a heap allocation + GC, passing it by value requires a bigger "memcpy". The cost of those copies can easily exceed the allocation/GC cost.

**Comment by c80k** [comment]
Any further comments on this? Otherwise, I'll close this issue.
