### ISSUE TITLE
.NET Standard runtime

### ISSUE THREAD

**Issue by lostinplace** [c80k/capnproto-dotnetcore#5]
I'd like to be able to use this for .NET and >NET Standard libraries, a version implemented for .NET standard would be great

**Comment by lostinplace** [comment]
Implemented in #4

**Comment by lostinplace** [comment]
bump

**Comment by c80k** [comment]
Sorry for the delay. I‘m still on vacation. Will return on Sunday and review the changes.

**Comment by c80k** [comment]
The multi-target solution (.NET Standard 2.0 + .NET Core 2.1) is now re-integrated into master, so this issue should be done.
