### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by obiben** [c80k/capnproto-dotnetcore#50]
Hey, I might be missing something obvious: how do I set a namespace for those classes to be generated in?

**Comment by c80k** [comment]
Hi, use the namespace attribute which is declared inside [csharp.capnp](https://github.com/c80k/capnproto-dotnetcore/blob/master/include/csharp.capnp). For details, see https://github.com/c80k/capnproto-dotnetcore/wiki/Customizing-generated-code-with-annotations
