### ISSUE TITLE
Is there a usage example somewhere? Trying to figure out how to deserialize from a file

### ISSUE THREAD

**Issue by anchpop** [c80k/capnproto-dotnetcore#54]
Sorry for the newb question. I'm trying to use Cap'n Proto as an interchange format for chromosomal data. My Cap'n Proto struct is called `ForRendering` (it's the struct that contains the information needed to render a chromosome). I'm able to serialize the data (that part is written in Python) and write it to a file, now I just have to read it. I think I almost have it working (the C# code is generated and whatnot), but I'm not sure how to actually deserialize, haha. 

```C#
byte[] data = File.ReadAllBytes(info_file_path);
var data_memory = new System.Memory<ulong>(data); // type error
var data_list = new List<System.Memory<ulong>> { data_memory }.AsReadOnly();
var ForRendering = ForRendering.READER.create(DeserializerState.CreateRoot(new WireFrame(data_list))); // needs an IReadOnlyList<Memory<ulong>>
```

My guess is that there's something I can do to get a value of type `IReadOnlyList<Memory<ulong>>` from one of type `byte[]`, but despite all my googling (and trying to read the benchmark and test code) I cannot figure out what it should be. Any help?

**Comment by anchpop** [comment]
Update: I tried this:

```C#
byte[] data = File.ReadAllBytes(info_file_path);
ulong[] data_u = Enumerable.Range(0, data.Length / (sizeof(ulong) / sizeof(byte))).Select((i) => System.BitConverter.ToUInt64(data, i)).ToArray();
var data_memory = new System.Memory<ulong>(data_u);
var data_list = new List<System.Memory<ulong>> { data_memory }.AsReadOnly();
var for_rendering = ForRendering.READER.create(DeserializerState.CreateRoot(new WireFrame(data_list)));
```

Which typechecks, but doesn't work. Trying to access any field fails with:
```
DeserializationException: This is not a struct
Capnp.DeserializerState.StructReadPointer (System.Int32 index) (at <381417829c14467cadc4f0fee00422a1>:0)
```

**Comment by c80k** [comment]
You might refer to the example code [Wiki example application (non RPC)](https://github.com/c80k/capnproto-dotnetcore/wiki/Example-application-(non-RPC)). Something like this:

```
using var fs = File.OpenRead(info_file_path);
var frame = Framing.ReadSegments(fs);
var deserializer = DeserializerState.CreateRoot(frame);
var for_rendering = new ForRendering.READER(deserializer);
```

**Comment by anchpop** [comment]
Oh, I didn't even see the wiki, thank you! I'll implement this first thing tomorrow then close this issue
