### ISSUE TITLE
How to deserialize to a domain class?

### ISSUE THREAD

**Issue by anchpop** [c80k/capnproto-dotnetcore#55]
Reading the [wiki](https://github.com/c80k/capnproto-dotnetcore/wiki/Example-application-(non-RPC)), it's clear how to create a domain class from whole cloth, but not how to create one from a deserialized READER class (or how to deserialize to a domain class directly). But elsewhere in the wiki it implies this is possible.

> However, using [a domain class] costs some serialization/deserialization overhead compared to using the reader/writer classes directly.

I ask because the schema I would like to use heavily relies on generics, which the docs say are more ergonomic to use within domain classes. Any help?

**Comment by c80k** [comment]
Hi! 
You might use the following snippet (assuming "AddressBook" is the domain class, and "stream" represents the Stream to deserialize from):

```csharp
var frame = Framing.ReadSegments(stream);
var deserializer = DeserializerState.CreateRoot(frame);
var book = CapnpSerializable.Create<AddressBook>(deserializer);

```
Regards,
Christian

**Comment by anchpop** [comment]
Thank you!
