### ISSUE TITLE
Getting started help: csharp.capnp

### ISSUE THREAD

**Issue by Zannick** [c80k/capnproto-dotnetcore#67]
Hello, I am trying to get started by setting a namespace for my codegen, per the documentation (and #50), but 

```capnp
using CSharp = import "/csharp.capnp";
```

fails with "Import failed."

I see this file is in the `include` directory of this project, but I only set up the user mode based on the README:
* MSBuild integration: capnp tool suite from choco & the MSBuild package
* the backend generator dotnet tool
* the runtime assembly

I cannot find a csharp.capnp file in any of these places. Is there another path required to reference it as an embedded resource of some kind?

**Comment by c80k** [comment]
Hi,
it's in the "include" directory of the repo, see here: https://github.com/c80k/capnproto-dotnetcore/blob/master/include/csharp.capnp

**Comment by Zannick** [comment]
Yes... how am I meant to include it via the install procedures?

**Comment by c80k** [comment]
It's meant to be drawn directly from the repo, there is currently no deployment for it.
